name: EKS Cluster Creation

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: 'Cluster Name'
        required: true
      region:
        description: 'AWS Region'
        required: true
      kops_state_store:
        description: 'kops state store'
        required: true
jobs:
  create-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      

      - name: Install eksctl
        run: |
          curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
          chmod +x kops
          sudo mv kops /usr/local/bin/kops
        
       

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

     
      - name: Create KOPs Cluster
        run: |
             export NAME=${{ inputs.cluster_name }}
             export KOPS_STATE_STORE=s3://${{ inputs.kops_state_store}}
             kops create cluster $NAME \
                 --zones "us-east-1a,us-east-1b,us-east-c" \
                 --master-zones "us-east-1a,us-east-1b,us-east-1c" \
                 --networking calico \
                 --topology private \
                 --bastion \
                 --node-count 3 \
                 --node-size t2.micro \
                 --kubernetes-version v1.6.6 \
                 --master-size t2.micro \
                 --dry-run \
                 -o yaml > $NAME.yaml
        

      
