name: EKS Cluster Creation

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: 'Cluster Name'
        required: true
      region:
        description: 'AWS Region'
        required: true

jobs:
  create-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      


      - name: Set environment variables
        run: |
            echo "CLUSTER_NAME=${{ github.event.inputs.cluster-name }}" >> $GITHUB_ENV
            echo "REGION=${{ github.event.inputs.region }}" >> $GITHUB_ENV
            echo "PUB_KEY=${{ secrets.PUB_KEY }}" >> $GITHUB_ENV

      - name: Install eksctl
        run: |
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo  mv /tmp/eksctl /usr/local/bin
            eksctl version
       

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
       
      - name: Create EKS Cluster
        run: |
          eksctl create cluster -f cluster.yaml

      - name: Configure kubectl
        run: aws eks --region ${{ inputs.region }} update-kubeconfig --name ${{ inputs.cluster-name }}

      - name: Verify Cluster
        run: kubectl get nodes
